// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bepfythffyyzvazxakvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcGZ5dGhmZnl5enZhenhha3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzU2MDYsImV4cCI6MjA3Mzk1MTYwNn0.snXkbJcxp19j8KR7DUJ6wom3rls5lHIgqy62xUyp_aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});